name: Input
on: 
  workflow_dispatch:
    inputs:
      workflow_data:
        description: "data"
        required: true
        default: ""
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute
        run: python run.py ${{ github.event.inputs.data }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
