name: Run scriptt
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  getdata:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt
      - run: python .github/script.py
        env:
          DEFAULT_BRANCH: main
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOKEN: ${{ secrets.TOKEN }}
          MAT: ${{ secrets.MAT }}
          PIN: ${{ secrets.PIN }}
